spring:
  cloud:
    stream:
      schemaRegistryClient:
        endpoint: 192.168.99.101:8081
      kafka:
        binder:
          brokers: 192.168.99.101:19092,192.168.99.102:29092,192.168.99.103:39092
      schema:
        avro:
          dynamicSchemaGenerationEnabled: true
      defaultBinder: kafka
      bindings:
        input:
          group: filter
          destination: filtered
          contentType: application/json;application/*+avro

server:
  port: 0
